docker stop ca.consumer.pharma-network.com
docker stop ca.manufacturer.pharma-network.com
docker stop ca.distributor.pharma-network.com
docker stop ca.retailer.pharma-network.com
docker stop ca.transporter.pharma-network.com
docker stop peer0.consumer.pharma-network.com
docker stop peer1.consumer.pharma-network.com
docker stop peer0.manufacturer.pharma-network.com
docker stop peer1.manufacturer.pharma-network.com
docker stop peer0.distributor.pharma-network.com
docker stop peer1.distributor.pharma-network.com
docker stop peer0.retailer.pharma-network.com
docker stop peer1.retailer.pharma-network.com
docker stop peer0.transporter.pharma-network.com
docker stop peer1.transporter.pharma-network.com
docker stop orderer.pharma-network.com
docker stop chaincode
docker stop cli