docker start ca.consumer.pharma-network.com
docker start ca.manufacturer.pharma-network.com
docker start ca.distributor.pharma-network.com
docker start ca.retailer.pharma-network.com
docker start ca.transporter.pharma-network.com
docker start peer0.consumer.pharma-network.com
docker start peer1.consumer.pharma-network.com
docker start peer0.manufacturer.pharma-network.com
docker start peer1.manufacturer.pharma-network.com
docker start peer0.distributor.pharma-network.com
docker start peer1.distributor.pharma-network.com
docker start peer0.retailer.pharma-network.com
docker start peer1.retailer.pharma-network.com
docker start peer0.transporter.pharma-network.com
docker start peer1.transporter.pharma-network.com
docker start orderer.pharma-network.com
docker start chaincode
docker start cli